export const BookCollection = [
    {
        name: 'Black Clover',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91WgpA0pjOL.jpg',
        totalVolumes: 23,
    },
    {
        name: 'My Hero Academia',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        totalVolumes: 32,
    },
    {
        name: 'Demon Slayer',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/81ZNkhqRvVL.jpg',
        totalVolumes: 25,
    },
    {
        name: 'Edens Zero',
        coverImageUrl: 'https://m.media-amazon.com/images/I/51G9+MEdlgL.jpg',
        totalVolumes: 5,
    },
];

export const Book = [
    {
        bookCollectionId: 1,
        name: 'Black Clover Vol. 1',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91WgpA0pjOL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 1,
        name: 'Black Clover Vol. 2',
        coverImageUrl: 'https://m.media-amazon.com/images/I/61qhq6E1aPL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 1,
        name: 'Black Clover Vol. 3',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51E6uhtgwYL._SX339_BO1,204,203,200_.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 1,
        name: 'Black Clover Vol. 4',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51673-0lK8L._SX340_BO1,204,203,200_.jpg',
        have: false,
        read: false,
        price: '2990',
        paidPrice: '',
    },
    {
        bookCollectionId: 1,
        name: 'Black Clover Vol. 5',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91o0dBQ8VpL.jpg',
        have: false,
        read: false,
        price: '2990',
        paidPrice: '',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 1',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 2',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 3',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 4',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 5',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 6',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: false,
        read: false,
        price: '2990',
        paidPrice: '',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 7',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 8',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 9',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71bELfIWTDL.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 10',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/81i5ITztl8L.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 11',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/81x5vnSiRhL.jpg',
        have: false,
        read: false,
        price: '2990',
        paidPrice: '0',
    },
    {
        bookCollectionId: 2,
        name: 'My Hero Academia Vol. 12',
        coverImageUrl: 'https://m.media-amazon.com/images/I/51beY7HdmxL.jpg',
        have: false,
        read: false,
        price: '2990',
        paidPrice: '0',
    },
    {
        bookCollectionId: 3,
        name: 'Demon Slayer Vol. 1',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51QOd2372JL._SX336_BO1,204,203,200_.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 3,
        name: 'Demon Slayer Vol. 2',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51QOd2372JL._SX336_BO1,204,203,200_.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 3,
        name: 'Demon Slayer Vol. 3',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51QOd2372JL._SX336_BO1,204,203,200_.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 3,
        name: 'Demon Slayer Vol. 4',
        coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51QOd2372JL._SX336_BO1,204,203,200_.jpg',
        have: true,
        read: false,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 4,
        name: 'Edens Zero. 1',
        coverImageUrl: 'https://m.media-amazon.com/images/I/51G9+MEdlgL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 4,
        name: 'Edens Zero. 2',
        coverImageUrl: 'https://m.media-amazon.com/images/I/51JEF4SAJNL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 4,
        name: 'Edens Zero. 3',
        coverImageUrl: 'https://m.media-amazon.com/images/I/51QizzxOyyL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 4,
        name: 'Edens Zero. 4',
        coverImageUrl: 'https://m.media-amazon.com/images/I/51OXzikzYIL.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
    {
        bookCollectionId: 4,
        name: 'Edens Zero. 5',
        coverImageUrl: 'https://m.media-amazon.com/images/I/51ORvO6ptML.jpg',
        have: true,
        read: true,
        price: '2990',
        paidPrice: '1550',
    },
];